# Generated by Django 5.0.4 on 2024-04-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advantage_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.FileField(null=True, upload_to='advantages', verbose_name='Иконка'),
        ),
    ]
