# Generated by Django 5.0.4 on 2024-04-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Добавить в раздел популярные туры?'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
