# Generated by Django 5.0.4 on 2024-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_destination_is_popular_alter_destination_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('excerpt', models.TextField(max_length=100, verbose_name='Краткое описание')),
                ('preview', models.ImageField(upload_to='tours/', verbose_name='Заставка')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('days', models.PositiveSmallIntegerField(verbose_name='Дней')),
                ('nights', models.PositiveSmallIntegerField(verbose_name='Ночей')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
