# Generated by Django 5.0.4 on 2024-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный тур?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый тур?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
