# Generated by Django 5.0.4 on 2024-04-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tour_is_popular_tour_is_recommended_tour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='excerpt',
        ),
    ]
