# Generated by Django 5.0.4 on 2024-04-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_tour_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('preview', models.ImageField(upload_to='articles/', verbose_name='Заставка')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
