# Generated by Django 5.0.4 on 2024-04-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_advantage_body_en_advantage_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.destination', verbose_name='Напрвление'),
        ),
    ]
