# Generated by Django 5.0.4 on 2024-04-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tour_short_descrtion_alter_tour_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='short_descrtion',
            new_name='short_description',
        ),
    ]
