# Generated by Django 5.0.4 on 2024-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_short_descrtion_tour_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='days',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Дней'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nights',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Ночей'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='preview',
            field=models.ImageField(null=True, upload_to='tours/', verbose_name='Заставка'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Стоимость'),
        ),
    ]
