# Generated by Django 5.0.4 on 2024-04-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tour_days_alter_tour_nights_alter_tour_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
    ]
