# Generated by Django 5.0.4 on 2024-04-11 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tour_short_description_en_tour_short_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='tour',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
