# Generated by Django 5.0.4 on 2024-04-12 21:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_review_author_en_review_author_ru_review_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='full_description_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание 2'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
    ]
