# Generated by Django 5.0.4 on 2024-04-12 21:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tour_full_description_2_alter_tour_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='full_description_2_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание 2'),
        ),
        migrations.AddField(
            model_name='tour',
            name='full_description_2_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание 2'),
        ),
    ]
