# Generated by Django 5.0.4 on 2024-04-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tour_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для карты'),
        ),
    ]
