# Generated by Django 5.0.4 on 2024-04-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_tour_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='full_description_2',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='full_description_2_en',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='full_description_2_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='map_link',
        ),
    ]
