# Generated by Django 5.0.4 on 2024-04-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_hotelitem_name_en_hotelitem_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourWithPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Заставка')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дней')),
                ('nights', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ночей')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Тур с ценой',
                'verbose_name_plural': 'Туры с ценой',
            },
        ),
        migrations.RemoveField(
            model_name='tour',
            name='days',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
    ]
