# Generated by Django 5.0.4 on 2024-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tourwithprice_remove_tour_days_remove_tour_nights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourwithprice',
            name='full_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='full_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='full_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
