# Generated by Django 5.0.4 on 2024-04-16 22:21

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_tourwithprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonTourWithPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descr', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дополнительная экскурсия',
                'verbose_name_plural': 'Дополнительные экскурсии',
            },
        ),
        migrations.CreateModel(
            name='DayTourWithPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descr', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'День тура',
                'verbose_name_plural': 'Дни тура',
            },
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='route',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка маршрута тура'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='Звездность'),
        ),
        migrations.AlterField(
            model_name='tourwithprice',
            name='full_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='tourwithprice',
            name='full_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='tourwithprice',
            name='full_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Детали'),
        ),
        migrations.CreateModel(
            name='PlacesTourWithPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место посещения')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Место посещения тура',
                'verbose_name_plural': 'Места посещений тура',
            },
        ),
    ]
