# Generated by Django 5.0.4 on 2024-04-16 22:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_addontourwithprice_daytourwithprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addontourwithprice',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='daytourwithprice',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='placestourwithprice',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур'),
        ),
        migrations.CreateModel(
            name='TourCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='TourHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='TourPriceDoesNotInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='TourPriceInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур')),
            ],
        ),
    ]
