# Generated by Django 5.0.4 on 2024-04-16 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_addontourwithprice_tour_daytourwithprice_tour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcondition',
            options={'verbose_name': 'Условие тура', 'verbose_name_plural': 'Условия тура'},
        ),
        migrations.AlterModelOptions(
            name='tourhotel',
            options={'verbose_name': 'Отель тура', 'verbose_name_plural': 'Отели тура'},
        ),
        migrations.AlterModelOptions(
            name='tourpricedoesnotinclude',
            options={'verbose_name': 'Цена не включает', 'verbose_name_plural': 'Цена не включает'},
        ),
        migrations.AlterModelOptions(
            name='tourpriceinclude',
            options={'verbose_name': 'Цена включает', 'verbose_name_plural': 'Цена включает'},
        ),
        migrations.CreateModel(
            name='PriceByHumanTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Количество человек')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tourwithprice', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Стоимость с человека',
                'verbose_name_plural': 'Стоимость с человека',
            },
        ),
    ]
