# Generated by Django 5.0.4 on 2024-04-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_tourwithprice_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpricedoesnotinclude',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tourpriceinclude',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
