# Generated by Django 5.0.4 on 2024-04-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_tourcondition_text_alter_tourhotel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addontourwithprice',
            name='descr',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='daytourwithprice',
            name='descr',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
