# Generated by Django 5.0.4 on 2024-04-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_tourwithprice_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourwithprice',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Сделать рекомендуемым ?'),
        ),
    ]
