# Generated by Django 5.0.4 on 2024-04-22 20:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_tourwithprice_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='full_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='full_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
        migrations.AlterField(
            model_name='tourwithprice',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='tourwithprice',
            name='full_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='tourwithprice',
            name='full_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Детали'),
        ),
    ]
