# Generated by Django 5.0.4 on 2024-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_tour_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='map_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
