# Generated by Django 5.0.4 on 2024-04-22 21:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_tour_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='full_description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание 1'),
        ),
    ]
