# Generated by Django 5.0.4 on 2024-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_tour_full_description2_en_tour_full_description2_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourwithprice',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Стоимость'),
        ),
    ]
