# Generated by Django 4.2 on 2024-04-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_tourwithprice_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotelitem', verbose_name='ОТЕЛЬ')),
            ],
            options={
                'verbose_name': 'Услуги отеля',
            },
        ),
    ]
