# Generated by Django 4.2 on 2024-04-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_hotelitem_description_hotelgalley'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelGalley',
            new_name='HotelGallery',
        ),
    ]
