# Generated by Django 4.2 on 2024-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename_hotelgalley_hotelgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bun',
            options={'verbose_name': 'Услуга отеля', 'verbose_name_plural': 'Услуги отеля'},
        ),
        migrations.AlterModelOptions(
            name='hotelgallery',
            options={'verbose_name': 'Фото отеля', 'verbose_name_plural': 'Фото отеля'},
        ),
        migrations.AddField(
            model_name='bun',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='bun',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotelitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
