# Generated by Django 5.0.4 on 2024-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_bun_options_alter_hotelgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addontourwithprice',
            name='descr_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='addontourwithprice',
            name='descr_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='addontourwithprice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='addontourwithprice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='daytourwithprice',
            name='descr_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='daytourwithprice',
            name='descr_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='daytourwithprice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='daytourwithprice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='placestourwithprice',
            name='place_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Место посещения'),
        ),
        migrations.AddField(
            model_name='placestourwithprice',
            name='place_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Место посещения'),
        ),
        migrations.AddField(
            model_name='tourcondition',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='tourcondition',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
