# Generated by Django 5.0.4 on 2024-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_addontourwithprice_descr_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpricedoesnotinclude',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='tourpricedoesnotinclude',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='tourpriceinclude',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='tourpriceinclude',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
