# Generated by Django 5.0.4 on 2024-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_tourpricedoesnotinclude_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourwithprice',
            name='season_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='tourwithprice',
            name='season_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон'),
        ),
    ]
