# Generated by Django 4.2 on 2024-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_tourwithprice_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebyhumantour',
            name='category_of_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория для цены'),
        ),
    ]
