# Generated by Django 4.2 on 2024-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_tourwithprice_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourwithprice',
            name='route',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка маршрута тура'),
        ),
    ]
