# Generated by Django 4.2 on 2024-10-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Туры в Узбекистан с Canaan-travel', max_length=100, verbose_name='Заголовок первой секции')),
                ('hero_subtitle', models.CharField(default='Откройте для себя сказочный Восток!', max_length=100, verbose_name='Подзаголовок первой секции')),
                ('hero_years', models.CharField(default='17', max_length=100, verbose_name='Лет на рынке')),
                ('hero_hotel_total', models.CharField(default='500+', max_length=100, verbose_name='Кол-во отелей')),
                ('hero_guides_total', models.CharField(default='300+', max_length=100, verbose_name='Кол-во гидов')),
                ('section_title_1', models.CharField(default='Популярные направления', max_length=100, verbose_name='Заголовок секции "Популярные направления"')),
                ('section_title_2', models.CharField(default='Популярные туры', max_length=100, verbose_name='Заголовок секции "Популярные туры"')),
                ('special_offer_text', models.CharField(default='Специальное предложение', max_length=100)),
                ('special_offer_text_2', models.CharField(default='Путешествуйте дешевле!', max_length=100)),
                ('we_recommend_title', models.CharField(default='Мы рекомендуем', max_length=100)),
                ('know_more_block', models.CharField(default='Узнайте больше о востоке', max_length=100)),
                ('know_more_block_2_title', models.CharField(default='Узнайте о востоке больше вместе с нами', max_length=100)),
                ('know_more_block_2_text', models.TextField(default='Canaan-travel — туристическая компания полного цикла, ставящая перед собой цель открыть красоту всего мира для каждого человека сегодня. Мы стремимся ближе познакомить Восток и Запад, предлагая путешествия по Центральной Азии туристам из СНГ, Европы и Америки и поездки по всему миру жителям Центральной Азии.\n\nМы работаем как с отдельными туристами, так и с компаниями. Наличие собственных авиакассы, автотранспорта и сотрудничество с лучшими гидами и отелями помогают нам формировать уникальные предложения в индивидуальном порядке.')),
                ('advantages_title', models.CharField(default='Преимущества нашего обслуживания', max_length=100)),
                ('email_resend_title', models.CharField(default='Подпишись на рассылку интересных предложений', max_length=100)),
                ('booking_block_title', models.CharField(default='Хотите забронировать тур?', max_length=100)),
                ('booking_block_text', models.CharField(default='Заполните небольшую форму и мы подберем тур именно для вас', max_length=150)),
                ('our_partners_title', models.CharField(default='Наши партнеры', max_length=150)),
                ('footer_text', models.TextField(default='Информация туристам Туры в Узбекистан Достопримечательности.\nНаша компания имеет все необходимые лицензии и сертификаты качества.\n\nНезависимые отзывы о нас читайте на TripAdvisor')),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
            },
        ),
    ]
