# Generated by Django 4.2 on 2024-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_alter_homepagestatic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMissionStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Наша миссия', max_length=100)),
                ('page_content', models.TextField()),
            ],
            options={
                'verbose_name': 'Наша миссия',
                'verbose_name_plural': 'Наша миссия',
            },
        ),
    ]
