# Generated by Django 4.2 on 2024-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0003_ourmissionstatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmissionstatic',
            name='page_content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourmissionstatic',
            name='page_content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourmissionstatic',
            name='page_title_en',
            field=models.CharField(default='Наша миссия', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourmissionstatic',
            name='page_title_ru',
            field=models.CharField(default='Наша миссия', max_length=100, null=True),
        ),
    ]
