# Generated by Django 4.2 on 2024-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0004_ourmissionstatic_page_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPageStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Отели Узбекистана', max_length=100)),
                ('page_content', models.TextField()),
            ],
            options={
                'verbose_name': 'Страница отелей',
                'verbose_name_plural': 'Страница отелей',
            },
        ),
    ]
