# Generated by Django 4.2 on 2024-10-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0006_hotelpagestatic_page_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetailStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Детальная страница',
                'verbose_name_plural': 'Детальная страница',
            },
        ),
    ]
