# Generated by Django 4.2 on 2024-10-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0007_tourdetailstatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetailstatic',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdetailstatic',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
