# Generated by Django 4.2 on 2024-10-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0008_tourdetailstatic_text_en_tourdetailstatic_text_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPageStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Виза - информация туристам', max_length=100)),
                ('page_content', models.TextField()),
            ],
            options={
                'verbose_name': 'Страница "Информация туристам"',
                'verbose_name_plural': 'Страница "Информация туристам"',
            },
        ),
    ]
