# Generated by Django 4.2 on 2024-10-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0012_tourdetailstatic_price_include_block_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagestatic',
            name='hero_guides_total_en',
        ),
        migrations.RemoveField(
            model_name='homepagestatic',
            name='hero_guides_total_ru',
        ),
        migrations.RemoveField(
            model_name='homepagestatic',
            name='hero_hotel_total_en',
        ),
        migrations.RemoveField(
            model_name='homepagestatic',
            name='hero_hotel_total_ru',
        ),
        migrations.RemoveField(
            model_name='homepagestatic',
            name='hero_years_en',
        ),
        migrations.RemoveField(
            model_name='homepagestatic',
            name='hero_years_ru',
        ),
    ]
